# Generated by Django 3.2.7 on 2021-09-16 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(default='Images/None/sampleImg.jpg', upload_to='Images'),
        ),
    ]
